# 微信小程序相关配置
[config.wechat]
    EnableAccessInterceptor = true
    EnableAccessInterceptorRes = true
    appId = ""
    appSecret = ""
    debug = true
    encodingAESKey = ""
    payKey = ""
    payMchId = ""
    payNotifyURL = ""
    token = ""
[redis.test]
    debug = true # ego增加redis debug，打开后可以看到，配置名，地址，耗时，请求数据，响应数据
    addr = ""
    enableAccessInterceptor = true
    enableAccessInterceptorReq = true
    enableAccessInterceptorRes = true
    password = ""